Fix error when using Symfony Routing component annotations
A controller using "Symfony\Component\Routing\Annotation\Route" instead of "Sensio\Bundle\FrameworkExtraBundle\Configuration\Route", with a prefix annotation on the class:

/**
 * @Route("/prefix")
 */
class SomeController { }

would cause an error:

Fatal error: Call to undefined method Symfony\Component\Routing\Annotation\Route::getService() in /vendor/sensio/framework-extra-bundle/Sensio/Bundle/FrameworkExtraBundle/Routing/AnnotatedRouteControllerLoader.php on line 40